### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue-ssr-webpack-plugin#7]
I get the following error while webpack is building:

```
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Compiler.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-ssr-webpack-plugin/lib/server.js:21:30)
    at Compiler.next (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:69:14)
    at /Users/callumacrae/Sites/samknows/website-vue/node_modules/html-webpack-plugin/index.js:205:9
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Compiler.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/html-webpack-plugin/index.js:204:15)
    at Compiler.applyPluginsAsync (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compiler.js:226:7)
    at Compiler.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compiler.js:184:10)
    at /Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
    at Compilation.applyPluginsAsync (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/callumacrae/Sites/samknows/website-vue/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/callumacrae/Sites/samknows/website-vue/node_modules/extract-text-webpack-plugin/index.js:309:4)
```

Relevant bits of my webpack config:

```
var webpackConfig = merge(baseWebpackConfig, {
  module: {
    loaders: utils.styleLoaders({ sourceMap: true, extract: true }),
  },
  target: 'node',
  devtool: '#source-map',
  output: {
    path: path.resolve(__dirname, '../dist'),
    filename: 'static/js/[name].[chunkhash].js',
    libraryTarget: 'commonjs2',
  },
  vue: {
    loaders: utils.cssLoaders({
      sourceMap: true,
      extract: true,
    }),
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        drop_debugger: true,
        warnings: false,
      },
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new ExtractTextPlugin('static/css/[name].[contenthash].css'),
    new HtmlWebpackPlugin({
      filename: path.resolve(__dirname, '../dist/index.html'),
      template: 'index.html',
      inject: true,
    }),
    new VueSSRServerPlugin(),
  ],
});
```

Any ideas what could be causing it? Sorry for the wall of text - really not sure what could be doing this.

**Comment by yyx990803** [comment]
FYI this plugin will be pulled into `vue-server-renderer` in 2.3, and there will be a full ssr guide. After 2.3 we are going to be working on ssr-compatible vue-cli templates.

**Comment by callumacrae** [comment]
Cool :) let me know if there's anything suitable for a first-time Vue contributor to work on (even if it's just documentation).
